pipeline {
    agent any 

    environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
        string(name: 'inventory', defaultValue: 'dev', description: 'This is where you chose your inventory')
    }

    stages {
        stage('initial cleanup') {
            steps {
                dir("$WORKSPACE") {
                    DeleteDir()
                }
            }
        }
        stage('GIT SCM') {
            steps {
                git branch: 'master', url: 'https://github.com/royalt1234/artifactory.git'
            }
        }
        stage('prepare ansible for execution') {
            steps {
                sh 'echo ${WORKSPACE}'
                sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" "${WORKSPACE}/deploy/ansible.cfg"'
            }
        }
        stage('Run Ansible') {
            steps {
                ansiblePlaybook become: true, colorized: true, credentialsId: 'ssh-keys-ansible', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
            }
        }
        stage('Clean Workspace') {
            steps {
                CleanWS()
            }
        }
    }
}
