pipeline {
    agent any

    stages {
        stage('testing work') {
            steps {
                script  {
                    sh'echo "testing stage"'
                }
            }
        }
        stage('all works') {
            steps {
                sh'echo "more testing ongoing"'
            }
        }
        stage('build') {
            steps {
                sh'echo "this is build stage"'
            }
        }
        stage('test') {
            steps {
                sh'echo "this is the test stage"'
            }
        }
        stage('package') {
            steps {
                sh'echo "this is a package stage"'
            }
        }
        stage('deploy') {
            steps {
                sh'echo "this is a deploy stage"'
            }
        }
    }
}